### ISSUE TITLE
json.decoder.JSONDecodeError when executing manageFishData.py

### ISSUE THREAD

**Issue by Akurosia** [icykoneko/ff14-fish-tracker-app#13]
> PS C:\Users\denterling\Documents\GitHub\ff14-fish-tracker-app> py ./private/manageFishData.py rebuild -i ./private/fishData.yaml -o ./js/app/data.js --with-icons -gpath "E:\FINAL FANTASY XIV - A Realm Reborn"
INFO:root:Getting data for: exd/root.exl
C:\Users\user\Documents\GitHub\ff14-fish-tracker-app\private\saintcoinach-py\pysaintcoinach\ex.json
Traceback (most recent call last):
  File "./private/manageFishData.py", line 379, in <module>
    initialize_data(args)
  File "./private/manageFishData.py", line 86, in initialize_data
    XIV = load_dats(args)
  File "./private/manageFishData.py", line 57, in load_dats
    xiv = ARealmReversed(args.game_path, Language.english)
  File "C:\Users\user\Documents\GitHub\ff14-fish-tracker-app\private\saintcoinach-py\pysaintcoinach\__init__.py", line 59, in __init__
    self._game_data.definition = RelationDefinition.from_json_fp(f)
  File "C:\Users\user\Documents\GitHub\ff14-fish-tracker-app\private\saintcoinach-py\pysaintcoinach\ex\relational\definition\__init__.py", line 741, in from_json_fp
    obj = json.load(fp)
  File "C:\Program Files (x86)\Python37-32\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files (x86)\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by icykoneko** [comment]
If you are running on Windows, make sure you've enabled symlinks.
Check this out: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

**Comment by icykoneko** [comment]
I've updated all of the README.md with notes, and did a fresh, clean clone to test it.  You should be able to build fine now.  It's mostly the symlinks causing issues.  They seemed cool at the time lolz.
